BINANCE_API_KEY = "CuVmctN2uOm1Ek2kek3kOHjm2q2jJ6QPLOZZSKPZuNf5aNrT2Gl3OhbDoVHVoijN"

BINANCE_SECRET = "8JKOdcyvUVWUfUYklYvs6ZaQTVeDfXMvp3PAGaklhkwyyVrfPy1QCARuvJiIUVCk"



FTX_API_KEY = 'fTY97VPuQZf-WluE8J-57fwOatMJ4_z6KE1hN_0E'
FTX_SECRET = 'A7UYTp3zzYmBLSDRZBkPP9jeFXR7o_s5y-KkzzIi'